"""initial_schema

Revision ID: 6f4e3554a006
Revises: c9e82f42b60f
Create Date: 2026-05-11 07:29:20.546114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4e3554a006'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_scaling_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('comparison', sa.String(length=20), nullable=False),
    sa.Column('min_replicas', sa.Integer(), nullable=False),
    sa.Column('max_replicas', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('target_resource_type', sa.String(length=50), nullable=False),
    sa.Column('target_resource_id', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cluster_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cluster_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metric_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_records_metric_name'), 'metric_records', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metric_records_project_id'), 'metric_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_metric_records_recorded_at'), 'metric_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_metric_records_source'), 'metric_records', ['source'], unique=False)
    op.create_table('migration_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('migration_type', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('destination_ref', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('target_action', sa.String(length=100), nullable=False),
    sa.Column('target_resource_type', sa.String(length=50), nullable=True),
    sa.Column('target_resource_id', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pool_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_capacity_gb', sa.Integer(), nullable=False),
    sa.Column('used_capacity_gb', sa.Integer(), nullable=False),
    sa.Column('replication_factor', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_pools')
    op.drop_table('scheduled_tasks')
    op.drop_table('resource_snapshots')
    op.drop_table('operation_tasks')
    op.drop_table('migration_tasks')
    op.drop_index(op.f('ix_metric_records_source'), table_name='metric_records')
    op.drop_index(op.f('ix_metric_records_recorded_at'), table_name='metric_records')
    op.drop_index(op.f('ix_metric_records_project_id'), table_name='metric_records')
    op.drop_index(op.f('ix_metric_records_metric_name'), table_name='metric_records')
    op.drop_table('metric_records')
    op.drop_table('cluster_deployments')
    op.drop_table('auto_scaling_policies')
    op.drop_table('audit_logs')
    op.drop_table('alert_records')
    # ### end Alembic commands ###
